version: 2

build:
    image: latest

sphinx:
    configuration: doc/conf.py
    builder: html
    fail_on_warning: true

formats:
    -pdf   
    
python:
    version: 3.8
    install:
        -requirements: requirements.txt
        -method: pip
         path: isoplot
         extra_requirements:
            -Sphinx
            -sphinx-argparse
            -sphinx-rtd-theme
            -autodoc


            